### ISSUE TITLE
Chrome crashing on android mobile

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/hydration-ui#1427] opened 2024-06-20 19:27 UTC
Getting AW SNAP error message on chrome mobile on https://app.hydration.net/trade/swap when trying to select the second asset on the trade page. It does not do the same on Nova.

![Screenshot_20240620_201903_Chrome](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/5bf45301-f600-42cc-9fa4-b86007cf7892)

![Screenshot_20240620_201836_Chrome](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/d6583ea6-e5dd-489d-997d-e05ca4f8ab65)

**Comment by DuriSK** [comment] 2024-07-12 12:00
fixed in https://deploy-preview-1492--edge-hydra-app.netlify.app/trade/swap
Issue seems to be solved with fix, was not able to reproduce during testing

**Closed by DuriSK** 2024-07-12 12:00 UTC
Labels: type/bug, priority/high, area/ui
